# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rtf_pb2 as rtf__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rtf_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RTFServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeClient = channel.unary_unary(
                '/document.RTFService/InitializeClient',
                request_serializer=rtf__pb2.InitializeRequest.SerializeToString,
                response_deserializer=rtf__pb2.DocumentContent.FromString,
                _registered_method=True)
        self.SyncChanges = channel.stream_stream(
                '/document.RTFService/SyncChanges',
                request_serializer=rtf__pb2.SyncChange.SerializeToString,
                response_deserializer=rtf__pb2.DocumentChange.FromString,
                _registered_method=True)
        self.SendLocalChange = channel.unary_unary(
                '/document.RTFService/SendLocalChange',
                request_serializer=rtf__pb2.DocumentChange.SerializeToString,
                response_deserializer=rtf__pb2.AckMessage.FromString,
                _registered_method=True)


class RTFServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncChanges(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLocalChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RTFServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeClient': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeClient,
                    request_deserializer=rtf__pb2.InitializeRequest.FromString,
                    response_serializer=rtf__pb2.DocumentContent.SerializeToString,
            ),
            'SyncChanges': grpc.stream_stream_rpc_method_handler(
                    servicer.SyncChanges,
                    request_deserializer=rtf__pb2.SyncChange.FromString,
                    response_serializer=rtf__pb2.DocumentChange.SerializeToString,
            ),
            'SendLocalChange': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLocalChange,
                    request_deserializer=rtf__pb2.DocumentChange.FromString,
                    response_serializer=rtf__pb2.AckMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document.RTFService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('document.RTFService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RTFService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.RTFService/InitializeClient',
            rtf__pb2.InitializeRequest.SerializeToString,
            rtf__pb2.DocumentContent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncChanges(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/document.RTFService/SyncChanges',
            rtf__pb2.SyncChange.SerializeToString,
            rtf__pb2.DocumentChange.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLocalChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.RTFService/SendLocalChange',
            rtf__pb2.DocumentChange.SerializeToString,
            rtf__pb2.AckMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LoggingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogChanges = channel.stream_unary(
                '/document.LoggingService/LogChanges',
                request_serializer=rtf__pb2.DocumentChange.SerializeToString,
                response_deserializer=rtf__pb2.LogResponse.FromString,
                _registered_method=True)


class LoggingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LogChanges(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogChanges': grpc.stream_unary_rpc_method_handler(
                    servicer.LogChanges,
                    request_deserializer=rtf__pb2.DocumentChange.FromString,
                    response_serializer=rtf__pb2.LogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document.LoggingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('document.LoggingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoggingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LogChanges(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/document.LoggingService/LogChanges',
            rtf__pb2.DocumentChange.SerializeToString,
            rtf__pb2.LogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
