# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: labyrinth.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'labyrinth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flabyrinth.proto\"\x07\n\x05\x45mpty\".\n\rLabyrinthInfo\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"S\n\x0cPlayerStatus\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\n\n\x02hp\x18\x03 \x01(\x05\x12\x12\n\nrem_spells\x18\x04 \x01(\x05\x12\r\n\x05score\x18\x05 \x01(\x05\" \n\x0bMoveRequest\x12\x11\n\tdirection\x18\x01 \x01(\t\"\x1e\n\x0cMoveResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"$\n\x0cTilePosition\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"&\n\x0eTargetPosition\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"9\n\x0eRevelioRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x11\n\ttile_type\x18\x03 \x01(\x05\"\"\n\x10\x42ombardaResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"!\n\x04Grid\x12\x19\n\x07gridrow\x18\x01 \x03(\x0b\x32\x08.GridRow\"\x16\n\x07GridRow\x12\x0b\n\x03val\x18\x01 \x03(\t2\x8e\x02\n\x10LabyrinthService\x12*\n\x10GetLabyrinthInfo\x12\x06.Empty\x1a\x0e.LabyrinthInfo\x12(\n\x0fGetPlayerStatus\x12\x06.Empty\x1a\r.PlayerStatus\x12+\n\x0cRegisterMove\x12\x0c.MoveRequest\x1a\r.MoveResponse\x12+\n\x07Revelio\x12\x0f.RevelioRequest\x1a\r.TilePosition0\x01\x12\x30\n\x08\x42ombarda\x12\x0f.TargetPosition\x1a\x11.BombardaResponse(\x01\x12\x18\n\x07GetGrid\x12\x06.Empty\x1a\x05.Gridb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'labyrinth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=19
  _globals['_EMPTY']._serialized_end=26
  _globals['_LABYRINTHINFO']._serialized_start=28
  _globals['_LABYRINTHINFO']._serialized_end=74
  _globals['_PLAYERSTATUS']._serialized_start=76
  _globals['_PLAYERSTATUS']._serialized_end=159
  _globals['_MOVEREQUEST']._serialized_start=161
  _globals['_MOVEREQUEST']._serialized_end=193
  _globals['_MOVERESPONSE']._serialized_start=195
  _globals['_MOVERESPONSE']._serialized_end=225
  _globals['_TILEPOSITION']._serialized_start=227
  _globals['_TILEPOSITION']._serialized_end=263
  _globals['_TARGETPOSITION']._serialized_start=265
  _globals['_TARGETPOSITION']._serialized_end=303
  _globals['_REVELIOREQUEST']._serialized_start=305
  _globals['_REVELIOREQUEST']._serialized_end=362
  _globals['_BOMBARDARESPONSE']._serialized_start=364
  _globals['_BOMBARDARESPONSE']._serialized_end=398
  _globals['_GRID']._serialized_start=400
  _globals['_GRID']._serialized_end=433
  _globals['_GRIDROW']._serialized_start=435
  _globals['_GRIDROW']._serialized_end=457
  _globals['_LABYRINTHSERVICE']._serialized_start=460
  _globals['_LABYRINTHSERVICE']._serialized_end=730
# @@protoc_insertion_point(module_scope)
