# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rtf.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'rtf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trtf.proto\x12\x08\x64ocument\"&\n\x11InitializeRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"4\n\nSyncChange\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63hangeIndex\x18\x02 \x01(\x05\"6\n\x0f\x44ocumentContent\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x12\n\nlastChange\x18\x02 \x01(\x05\"s\n\x0e\x44ocumentChange\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63hange_type\x18\x02 \x01(\t\x12\x10\n\x08position\x18\x03 \x01(\x05\x12\x12\n\ncharChange\x18\x04 \x01(\t\x12\x13\n\x0b\x63hangeIndex\x18\x05 \x01(\x05\"\x1d\n\nAckMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0bLogResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xde\x01\n\nRTFService\x12J\n\x10InitializeClient\x12\x1b.document.InitializeRequest\x1a\x19.document.DocumentContent\x12\x41\n\x0bSyncChanges\x12\x14.document.SyncChange\x1a\x18.document.DocumentChange(\x01\x30\x01\x12\x41\n\x0fSendLocalChange\x12\x18.document.DocumentChange\x1a\x14.document.AckMessage2Q\n\x0eLoggingService\x12?\n\nLogChanges\x12\x18.document.DocumentChange\x1a\x15.document.LogResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rtf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITIALIZEREQUEST']._serialized_start=23
  _globals['_INITIALIZEREQUEST']._serialized_end=61
  _globals['_SYNCCHANGE']._serialized_start=63
  _globals['_SYNCCHANGE']._serialized_end=115
  _globals['_DOCUMENTCONTENT']._serialized_start=117
  _globals['_DOCUMENTCONTENT']._serialized_end=171
  _globals['_DOCUMENTCHANGE']._serialized_start=173
  _globals['_DOCUMENTCHANGE']._serialized_end=288
  _globals['_ACKMESSAGE']._serialized_start=290
  _globals['_ACKMESSAGE']._serialized_end=319
  _globals['_LOGRESPONSE']._serialized_start=321
  _globals['_LOGRESPONSE']._serialized_end=351
  _globals['_RTFSERVICE']._serialized_start=354
  _globals['_RTFSERVICE']._serialized_end=576
  _globals['_LOGGINGSERVICE']._serialized_start=578
  _globals['_LOGGINGSERVICE']._serialized_end=659
# @@protoc_insertion_point(module_scope)
